/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/kamegoro/go-type-gen/go"
)

func main() {
	log.Printf("Server started")

	PetAPIService := openapi.NewPetAPIService()
	PetAPIController := openapi.NewPetAPIController(PetAPIService)

	StoreAPIService := openapi.NewStoreAPIService()
	StoreAPIController := openapi.NewStoreAPIController(StoreAPIService)

	UserAPIService := openapi.NewUserAPIService()
	UserAPIController := openapi.NewUserAPIController(UserAPIService)

	router := openapi.NewRouter(PetAPIController, StoreAPIController, UserAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
